### ISSUE TITLE
Create puzzle image for pennylane-qrack

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/pennylane-qrack#15]
It would be great to create a puzzle image for `pennylane-qrack` like [the one](https://github.com/nathanshammah/pennylane-qulacs/blob/master/doc/_static/puzzle_qulacs.png) for `pennylane-qulacs`. We can use the Qrack logo, which, as far as I know, can be found [here](https://github.com/vm6502q/qrack.net/blob/main/app/assets/img/qrack_logo.png). @josh146, shall we just paste the Qrack logo on top of the qulacs logo? Or you have an original file where maybe we can insert the image more nicely? Not sure if there is a way to remove the white background, or if @WrathfulSpatula has an svg / transparent background version (if this is not already the case for png). I also don't have image editing software. Also, maybe the other pieces of the puzzle should be changed / to include Catalyst / Jax, etc.

**Comment by josh146** [comment]
@nathanshammah we can help on our end come up with a new graphic showing PL / JAX / qjit / Qrack :) I'll get back to you on this one with some options.

**Comment by nathanshammah** [comment]
Fantastic, thanks @josh146!

**Comment by josh146** [comment]
Hi @nathanshammah @WrathfulSpatula, here are some images to choose from:

![image](https://github.com/unitaryfund/pennylane-qrack/assets/2959003/5c1132bc-4878-4bdf-93f5-03c4f697d394)

![image](https://github.com/unitaryfund/pennylane-qrack/assets/2959003/ec1dd666-b01e-4af3-9535-515bf4db599d)

**Comment by WrathfulSpatula** [comment]
Thank you! These have been added to the appropriate fields for the tutorial.
